<?php

/**
 * ArtisanPack UI Unified Configuration.
 *
 * This file is automatically generated by the artisanpack:scaffold-config command.
 * It contains the default settings from all installed ArtisanPack UI packages.
 * You can safely modify these values to customize your application.
 */
return [
    'icons' => [
        'default_set' => 'heroicon',
        'sets' => [],
    ],
    'livewire-ui-components' => [
        'prefix' => 'artisanpack',
        'route_prefix' => '',
        'components' => [
            'spotlight' => [
                'class' => 'App\\Support\\Spotlight',
            ],
        ],
        'icons' => [
            'list_item' => [
                'bullet' => 'o-minus',
                'checkmark' => 'o-check',
                'arrow' => 'o-chevron-right',
                'dot' => 'o-ellipsis-horizontal',
                'status' => [
                    'new' => 'o-sparkles',
                    'completed' => 'o-check-circle',
                    'error' => 'o-exclamation-triangle',
                    'warning' => 'o-exclamation-circle',
                    'info' => 'o-information-circle',
                ],
                'type' => [
                    'user' => 'o-user',
                    'file' => 'o-document',
                    'folder' => 'o-folder',
                    'email' => 'o-envelope',
                    'notification' => 'o-bell',
                ],
            ],
            'loading' => [
                'spinner' => 'o-arrow-path',
                'dots' => null,
                'ring' => null,
                'custom_svg' => null,
                'default_type' => 'css',
            ],
        ],
        'theme_output_path' => '/Users/jacobmartella/Herd/livewire-starter-kit/resources/css/artisanpack-ui-theme.css',
    ],
];
