<?php
/**
 * ArtisanPack UI Unified Configuration.
 *
 * This file is automatically generated by the artisanpack:scaffold-config command.
 * It contains the default settings from all installed ArtisanPack UI packages.
 * You can safely modify these values to customize your application.
 */
return [
    'core' => [
        'logging' => [
            'channel' => NULL,
            'audit' => [
                'enabled' => true,
            ],
        ],
    ],
    'accessibility' => [
        'wcag_thresholds' => [
            'aa' => 4.5,
            'aaa' => 7.0,
        ],
        'large_text_thresholds' => [
            'font_size' => 18,
            'font_weight' => 'bold',
        ],
        'cache' => [
            'default' => 'array',
            'stores' => [
                'array' => [
                    'driver' => 'array',
                    'limit' => 1000,
                ],
                'file' => [
                    'driver' => 'file',
                    'path' => '/Users/jacobmartella/Code/ArtisanPack UI Packages/livewire-starter-kit/storage/framework/cache/data/accessibility',
                ],
                'null' => [
                    'driver' => 'null',
                ],
            ],
        ],
        'roles' => [
            'admin' => [
                0 => 'view_reports',
                1 => 'manage_reports',
                2 => 'view_dashboard',
                3 => 'manage_teams',
            ],
            'editor' => [
                0 => 'view_reports',
                1 => 'manage_reports',
                2 => 'view_dashboard',
            ],
            'viewer' => [
                0 => 'view_reports',
                1 => 'view_dashboard',
            ],
        ],
        'audit' => [
            'paths' => [
                0 => '/Users/jacobmartella/Code/ArtisanPack UI Packages/livewire-starter-kit/resources/views',
                1 => '/Users/jacobmartella/Code/ArtisanPack UI Packages/livewire-starter-kit/resources/css',
                2 => '/Users/jacobmartella/Code/ArtisanPack UI Packages/livewire-starter-kit/public/css',
            ],
            'include_extensions' => [
                0 => 'css',
                1 => 'blade.php',
            ],
            'exclude' => [
                0 => 'vendor',
                1 => 'storage',
                2 => 'node_modules',
            ],
            'strictness' => 'AA',
        ],
        'report' => [
            'formats' => [
                0 => 'md',
            ],
            'output_path' => '/Users/jacobmartella/Code/ArtisanPack UI Packages/livewire-starter-kit/storage/app/a11y',
        ],
        'progress' => [
            'enabled' => true,
            'min_items_for_bar' => 50,
        ],
    ],
    'icons' => [
        'default_set' => 'heroicon',
        'sets' => [],
    ],
    'livewire-ui-components' => [
        'prefix' => 'artisanpack',
        'route_prefix' => '',
        'components' => [
            'spotlight' => [
                'class' => 'App\\Support\\Spotlight',
            ],
        ],
        'icons' => [
            'list_item' => [
                'bullet' => 'o-minus',
                'checkmark' => 'o-check',
                'arrow' => 'o-chevron-right',
                'dot' => 'o-ellipsis-horizontal',
                'status' => [
                    'new' => 'o-sparkles',
                    'completed' => 'o-check-circle',
                    'error' => 'o-exclamation-triangle',
                    'warning' => 'o-exclamation-circle',
                    'info' => 'o-information-circle',
                ],
                'type' => [
                    'user' => 'o-user',
                    'file' => 'o-document',
                    'folder' => 'o-folder',
                    'email' => 'o-envelope',
                    'notification' => 'o-bell',
                ],
            ],
            'loading' => [
                'spinner' => 'o-arrow-path',
                'dots' => NULL,
                'ring' => NULL,
                'custom_svg' => NULL,
                'default_type' => 'css',
            ],
        ],
        'theme_output_path' => '/Users/jacobmartella/Code/ArtisanPack UI Packages/livewire-starter-kit/resources/css/artisanpack-ui-theme.css',
    ],
];
